
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public final class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
     String newuserid,check;
    
    public ForgetPassword() {
        initComponents();
        
        con = Database_connection_CLASS.connection();
        
        
        
        step2.setVisible(false);
        step3.setVisible(false);
        

        massage.setVisible(false);
        massage1.setVisible(false);

    }
    
    public void updatepassword (){
    
        try{
            
            String Query = "UPDATE `users` SET `password` = ? WHERE `email` = ?;";

            PreparedStatement preparedStmt = con.prepareStatement(Query);
            preparedStmt.setString(1, pw1.getText());
            preparedStmt.setString(2, email.getText());
            preparedStmt.execute();
            step2.setVisible(false);
            step3.setVisible(true);
        
        }
        catch(SQLException e){
        
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        step1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        next1 = new javax.swing.JButton();
        massage = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        question = new javax.swing.JComboBox<>();
        answer = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        step2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        next2 = new javax.swing.JButton();
        massage1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pw2 = new javax.swing.JPasswordField();
        pw1 = new javax.swing.JPasswordField();
        step3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background-01.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        step1.setBackground(new java.awt.Color(255, 255, 255));
        step1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Sign in to Qize App using the details provided by your institute");
        step1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 380, 20));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        jLabel5.setText("Forget password");
        step1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 380, 44));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Your email ");
        step1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 380, 30));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Your security question");
        step1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 380, 30));

        next1.setText("Next");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        step1.add(next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 380, 40));

        massage.setText("jLabel2");
        step1.add(massage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 380, 30));
        step1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 380, 40));

        question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        step1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 380, 40));
        step1.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 380, 40));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Your answer");
        step1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 380, 30));

        jPanel1.add(step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 612, 520));

        step2.setBackground(new java.awt.Color(255, 255, 255));
        step2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Sign in to Qize App using the details provided by your institute");
        step2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 380, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        jLabel6.setText("New Password");
        step2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 380, 44));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Password ");
        step2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 380, 30));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Confirm password");
        step2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 380, 30));

        next2.setText("Confirm");
        next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2ActionPerformed(evt);
            }
        });
        step2.add(next2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 380, 40));

        massage1.setText("jLabel2");
        step2.add(massage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 380, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_back_30px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        step2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 40, 50));
        step2.add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 380, 40));
        step2.add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 380, 40));

        jPanel1.add(step2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 612, 430));

        step3.setBackground(new java.awt.Color(255, 255, 255));
        step3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_done_60px_1.png"))); // NOI18N
        jLabel21.setToolTipText("");
        step3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 80));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Congratulations!");
        step3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 50));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("You can log now and ready to use");
        step3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 520, 50));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Your account password has been successfully changed ");
        step3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 520, 50));

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        step3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, 40));

        jPanel1.add(step3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 612, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        // TODO add your handling code here:
        try{
        
            if( email.getText().equals("")||answer.getText().equals("")  )
            {

                massage.setVisible(true);
                Color orange = new Color(255,102,0);
                massage.setForeground(orange);
                massage.setText("Important feilds are missing!");
            }
            else
            {
                
                
                
                boolean loopcheck = false;

                stmt = con.createStatement();
                String query = "SELECT * FROM users ";

                String email2 = email.getText();
                String answer2 = answer.getText();
                String qy = question.getSelectedItem().toString();
                
                ResultSet rs = stmt.executeQuery(query);

                while(rs.next())
                {
                    if (email2.equals(rs.getString(3)) && qy.equals(rs.getString(6))  && answer2.equals(rs.getString(7)))
                    {


                        step1.setVisible(false);
                        step2.setVisible(true);
                        
                        
                    }
                }
                if(!loopcheck){

                    massage.setVisible(true);
                    massage.setVisible(true);
                    Color red = new Color(255,0,0);
                    massage.setForeground(red);
                    massage.setText("Provided details are doesnt match with our system details");
                }
                
                
                
            }
        }
        catch(SQLException e){
        
        }
    }//GEN-LAST:event_next1ActionPerformed

    private void next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2ActionPerformed
        // TODO add your handling code here:
        try{
        
            if( pw1.getText().equals("")|| pw2.getText().equals("")  )
                {

                    massage1.setVisible(true);
                    Color orange = new Color(255,102,0);
                    massage1.setForeground(orange);
                    massage1.setText("Important feilds are missing!");
                }
            else
            { 
                
                updatepassword();
                
            }
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_next2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try{
        
            step2.setVisible(false);
            step1.setVisible(true);
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{

            this.setVisible(false);
            Main Load = new Main ();
            Load.setVisible(true);
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel massage;
    private javax.swing.JLabel massage1;
    private javax.swing.JButton next1;
    private javax.swing.JButton next2;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JComboBox<String> question;
    private javax.swing.JPanel step1;
    private javax.swing.JPanel step2;
    private javax.swing.JPanel step3;
    // End of variables declaration//GEN-END:variables
}
