/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dinus
 */
public final class HomeUser extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    public static String type,userid;
    
    public HomeUser() {
        initComponents();
        
        
        ParticipateToQuiz.userid = userid;
        StudentQuizHistory.userid = userid;
        UserProfile.userid = userid;
        
        ParticipateToQuiz view = new ParticipateToQuiz ();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(view).setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentPane = new javax.swing.JPanel();
        addnew4 = new javax.swing.JButton();
        addnew6 = new javax.swing.JButton();
        addnew7 = new javax.swing.JButton();
        addnew8 = new javax.swing.JButton();
        addnew9 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-01.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_student_male_40px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 0, 120, 70));

        studentPane.setBackground(new java.awt.Color(255, 255, 255));

        addnew4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addnew4.setForeground(new java.awt.Color(51, 51, 51));
        addnew4.setText("Logout");
        addnew4.setContentAreaFilled(false);
        addnew4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addnew4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew4ActionPerformed(evt);
            }
        });

        addnew6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addnew6.setForeground(new java.awt.Color(51, 51, 51));
        addnew6.setText("Participate to Quiz");
        addnew6.setContentAreaFilled(false);
        addnew6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addnew6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew6ActionPerformed(evt);
            }
        });

        addnew7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addnew7.setForeground(new java.awt.Color(51, 51, 51));
        addnew7.setText("Quiz history");
        addnew7.setContentAreaFilled(false);
        addnew7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addnew7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew7ActionPerformed(evt);
            }
        });

        addnew8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addnew8.setForeground(new java.awt.Color(51, 51, 51));
        addnew8.setText("Profile");
        addnew8.setContentAreaFilled(false);
        addnew8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addnew8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew8ActionPerformed(evt);
            }
        });

        addnew9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addnew9.setForeground(new java.awt.Color(51, 51, 51));
        addnew9.setText("Profile");
        addnew9.setContentAreaFilled(false);
        addnew9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addnew9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addnew9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnew9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPaneLayout = new javax.swing.GroupLayout(studentPane);
        studentPane.setLayout(studentPaneLayout);
        studentPaneLayout.setHorizontalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addnew4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addnew6, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(addnew7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addnew8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addnew9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        studentPaneLayout.setVerticalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addnew6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addnew7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addnew8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(addnew9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, Short.MAX_VALUE)
                .addComponent(addnew4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addnew4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main load = new Main();
        load.setVisible(true);
    }//GEN-LAST:event_addnew4ActionPerformed

    private void addnew6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew6ActionPerformed
        // TODO add your handling code here:
        try
        {

            ParticipateToQuiz view = new ParticipateToQuiz ();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_addnew6ActionPerformed

    private void addnew7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew7ActionPerformed
        // TODO add your handling code here:
        try
        {

            StudentQuizHistory view = new StudentQuizHistory ();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_addnew7ActionPerformed

    private void addnew8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew8ActionPerformed
        // TODO add your handling code here:
        
        try
        {

            UserProfile view = new UserProfile ();
            jDesktopPane1.removeAll();
            jDesktopPane1.add(view).setVisible(true);

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_addnew8ActionPerformed

    private void addnew9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnew9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addnew9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnew4;
    private javax.swing.JButton addnew6;
    private javax.swing.JButton addnew7;
    private javax.swing.JButton addnew8;
    private javax.swing.JButton addnew9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel studentPane;
    // End of variables declaration//GEN-END:variables
}
