
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;



public final class StudentPreformance extends javax.swing.JLayeredPane {
    


    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public String value,QuizCode,Status,Byusers,userid2;
    
    public StudentPreformance(String quizecode,String userid) {
        

        initComponents();

         con = Database_connection_CLASS.connection();
         
        jLabel2.setText(quizecode);

        userid2 = userid;
        QuizCode = quizecode;
        
        calculateMarks ();
        QuizDetails();
        StudentDetaiils ();

        
    }
    
    public void QuizDetails (){
    
        try{
        
            stmt = con.createStatement();
            
            String query = "SELECT * FROM quizes";
            ResultSet rsd = stmt.executeQuery(query);
            
            while(rsd.next())
            {
                
                if(QuizCode.equals(rsd.getString(3))){
                    
                    jLabel3.setText(rsd.getString(2));
                    
                }
                
            }
        }
        catch(Exception e){
        
        }
    }
    
    public void StudentDetaiils (){
    
        try{
        
            stmt = con.createStatement();
            
            String query = "SELECT * FROM users";
            ResultSet rsd = stmt.executeQuery(query);
            System.out.println(userid2);
            while(rsd.next())
            {
                
                if(userid2.equals(rsd.getString(1))){
                    
                    name.setText(rsd.getString(8)+" "+rsd.getString(8));
                    
                }
                
            }
        }
        catch(Exception e){
        
        }
    }
    
    public void calculateMarks (){
    
        try{
        
            int count = 0;
            int CorrectAnswer = 0;
            stmt = con.createStatement();
            
            String query = "SELECT * FROM marks";
            ResultSet rsd = stmt.executeQuery(query);
            
            while(rsd.next())
            {
                if(QuizCode.equals(rsd.getString(1)) && userid2.equals(rsd.getString(3))){
                    count ++;
                    String cr = "Correct";
                    if (cr.equals(rsd.getString(5))){
                        CorrectAnswer++;
                    }
                }
                
            }
            float finaleMarks = (CorrectAnswer * 100)/count;
            jLabel1.setText(Float.toString(finaleMarks));
        }
        catch(Exception e){
        
        }
    }
    

    
    
    
    
    
    
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 226, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 5, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 960, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 48)); // NOI18N
        jLabel1.setText("100");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Marks");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 26));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("Quiz Code :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 111, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Titel");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 439, 26));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel3.setText("Active");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 1334, 37));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Student name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 439, 26));

        name.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        name.setText("Active");
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 1334, 37));

        setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
